name: Pull Request

on: [ pull_request ]

jobs:
  build:
    strategy:
      matrix:
        node:
          - 12
          - 14

    name: Build with Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory
        id: yarn-cache-directory
        run: |
          echo "::set-output name=path::$(yarn cache dir)"

      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
          path: |
            ${{ steps.yarn-cache-directory.outputs.path }}
            **/node_modules

      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory
        id: yarn-cache-directory
        run: |
          echo "::set-output name=path::$(yarn cache dir)"

      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
          path: |
            ${{ steps.yarn-cache-directory.outputs.path }}
            **/node_modules

      - name: Install dependencies
        run: |
          yarn install

      - name: Lint
        run: |
          yarn lint
